
#
# Configuration file for Travis CI
# https://travis-ci.org/
#

language: java

jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

after_success:
  - cd cel-plugin ; mvn clean cobertura:cobertura coveralls:report

sudo: false


